
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jeka
  password: qq22
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_blog_development

test:
  <<: *default
  database: rails_blog_test

